language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"

cache:
  directories:
    - test/games

services:
  - xvfb

before_install:
  - sudo apt-get -y install libxkbcommon-x11-0
  - sudo apt-get -y install libxcb-icccm4
  - sudo apt-get -y install libxcb-image0
  - sudo apt-get -y install libxcb-keysyms1
  - sudo apt-get -y install libxcb-randr0
  - sudo apt-get -y install libxcb-render-util0
  - sudo apt-get -y install libxcb-xinerama0

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade pip wheel
  - python3 -m pip install --upgrade setuptools
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install --upgrade coveralls

script:
  - cd test
  - coverage erase
  - coverage run --source hichess test/test_hichess.py -vv CellWidgetTestCase
  - coverage run --source hichess test/test_hichess.py -vv BoardWidgetTestCase
