language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"

cache:
  directories:
    - test/games

install:
  - pip install -r requirements.txt
  - pip install --upgrade setuptools
  - pip install --upgrade coveralls

script:
  - coverage erase
  - coverage run --source hichess test_hichess.py -vv CellWidgetTestCase
  - coverage run --source hichess test_hichess.py -vv BoardWidgetTestCase
