language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"

cache:
  directories:
    - test/games

install:
  - pip install -r requirements.txt
  - pip install --upgrade setuptools

script:
  - cd test
  - py test_hichess.py
